### ISSUE TITLE
express.js' cors working but tinyhttp's not

### ISSUE THREAD

**Issue by phtdacosta** [tinyhttp/cors#2]
Just by commenting ```"@tinyhttp/cors"``` and using express.js' cors instead, my application works, but somehow, when I comment express.js' cors to use tinyhttp's, the server starts rejecting everything. I am not using anything but the default ```.use(cors())```

![image](https://github.com/tinyhttp/cors/assets/8548534/b6e9aa01-6123-4774-a7a5-802e5c30b28d)

**Comment by aarontravass** [comment]
Could you please try making requests to `localhost:3002` instead of `127.0.0.1:3002`?

**Comment by phtdacosta** [comment]
Sure, but unfortunately it did not work too 😬

![image](https://github.com/tinyhttp/cors/assets/8548534/f6b47cf1-1f67-4488-824d-bb055ceeb0cc)

**Comment by aarontravass** [comment]
From which URL is the frontend application making a request to `localhost:3002`? Also, notice the first error

> header 'authorization' is not allowed....

You need to allow the authorization header. Add it in the `allowedHeaders` options.

**Comment by phtdacosta** [comment]
It was exactly the problem, not being "explicit" enough with the header, while express.js' cors lib seems to just allow everything by default. Not sure if it is a bug or feature in case of tinyhttp's cors but it seems another good warning to write in the CORS docs in here that it is not exactly plug-and-play with express.js'. Thank you so much, @aarontravass!
