### ISSUE TITLE
Passing `string[]` for `origin` option causes internal server error

### ISSUE THREAD

**Issue by Lordfirespeed** [tinyhttp/cors#4]
As title. 

Minimum reproduction:
```ts
import { App } from "@tinyhttp/app"
import { cors } from "@tinyhttp/cors"
import { logger } from "@tinyhttp/logger"

const app = new App()

app
  .use(logger())
  .use(cors({
    origin: ["http://localhost:3001"]
  }))
  .listen(3000, () => console.log(`Listening on http://localhost:3000`))
```

Now, requests to `http://localhost:3000` from the origin `http://localhost:3001` succeed (404 status) as intended

However, direct requests to `http://localhost:3000` fail (500 status on Firefox) because the Origin header is omitted from the request (value of `undefined`) which means [here](https://github.com/tinyhttp/cors/blob/57cf95f0072c46f97c7fbcbbfbd77f980bd768a6/src/index.ts#L38) `origin.indexOf(undefined)` always returns `-1`, leading to the rather confusing `No other objects allowed. Allowed types is array of strings or RegExp` error message

Proposed 'correct' behaviour when `origin` is a `string[]`:
- When the `Origin` header is excluded, CORS headers need not be attached to the response as the request is not cross-origin
- When the `Origin` header is included and present in the `origin` array, CORS headers should be attached to the response, including an `Access-Control-Allow-Origin` header whose value matches the value of the request's `Origin` header
- When the `Origin` header is included and not present in the `origin` array, no `Access-Control-Allow-Origin` header should be attached to the response

**Comment by aarontravass** [comment]
Thank you for reporting this issue. Would you like to open a pull request with the proposed changes?

**Comment by Lordfirespeed** [comment]
Sure!

**Comment by v1rtl** [comment]
I'm happy to merge/release a fix

**Comment by Lordfirespeed** [comment]
> I'm happy to merge/release a fix

@talentlessguy @aarontravass please let me know if there's anything else you need from my end 😄

**Comment by v1rtl** [comment]
@Lordfirespeed I've submitted a code review, there's a few minor things that could be improved
